version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: aw-demo
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo_db
    ports:
      - "8080:8080"
    restart: always
